files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - client-jquery/**/*.js
    - server-express/**/*.js
  # define files excluded from the analysis (defaults to [])
  excluded:
    - plugins/vendor/**/*.js
    - !regexp:/vendor/
